#!/bin/bash

if hash yap 2> /dev/null; then
    PROLOG=yap
else
    if hash swipl 2> /dev/null; then
        PROLOG=swipl
    else
        printf "neither yap nor swipl executeable found\n"
        exit 1
    fi
fi

if [ -z "$2" ]; then
    GOAL="time(a),halt"
else
    GOAL="$2,halt"
fi

$PROLOG -l $1 -g $GOAL
